CREATE TABLE IF NOT EXISTS usuario
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    primer_apellido VARCHAR(100) NOT NULL,
    segundo_apellido VARCHAR(100),
    ci INTEGER NOT NULL,
    ci_extension VARCHAR(10) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    user_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultima_actualizacion TIMESTAMPTZ,
    usuario_auditoria_id INTEGER,
    CONSTRAINT uq_usuario_ci UNIQUE (ci),
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT uq_usuario_user_name UNIQUE (user_name),
    CONSTRAINT fk_usuario_auditoria
        FOREIGN KEY (usuario_auditoria_id)
        REFERENCES usuario(id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_usuario_activo
    ON usuario (activo);

CREATE INDEX IF NOT EXISTS idx_usuario_ci
    ON usuario (ci);

CREATE INDEX IF NOT EXISTS idx_usuario_role
    ON usuario (role);

CREATE TABLE IF NOT EXISTS usuario_token
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    tipo_token VARCHAR(50) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMPTZ NOT NULL,
    revocado BOOLEAN NOT NULL DEFAULT FALSE,
    usado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_uso TIMESTAMPTZ,
    fecha_revocacion TIMESTAMPTZ,
    CONSTRAINT uq_usuario_token_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_usuario_token_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_usuario_token_usuario_tipo
    ON usuario_token (usuario_id, tipo_token);

CREATE INDEX IF NOT EXISTS idx_usuario_token_expiracion
    ON usuario_token (fecha_expiracion);

CREATE INDEX IF NOT EXISTS idx_usuario_token_estado
    ON usuario_token (revocado, usado);
